# Exploratory data analysis(EDA):

**EDA**: is a way of visualizing,summarizing and interpreting the information that is hidden in the data stored in rows and columns.
1. it helps uncovering patterns,relationships, and anomalies in the data.
2. EDA is used to achieve important insights and statistical measures that are essential for both business decision-making and data science projects.
3. Applying descriptive statistics and visualizations,EDA makes it easirer to understand the structure and meaning of data before moving to predective modeling or machine learning.

**Python Libraries that are helpful for EDA**:
1. **Numpy**: for fast handling of numbers and arrays of data.(perform mathematical and numerical operations in data analysis)
2. **Pandas**: Organize and analyze dta in table-like structures.(Data cleaning,handling missing values, and extracting insights).
3. **Matplotlib**: Create basic charts and plots.(visualize data with line plots,bar charts,scatter plots, distribution plots)
4. **Seaborn**: Build attractive and easy statistical plots.(Explore patterns and relationships with heatmaps, pair plots, distribution plots)

Numpy+Pandas=Data processing.
Matplotlib+Seaborn=Data visualization.

# Introduction to Numpy:

**Numpy**: is a linear algebra python library. short for numerical python. it is very important for data science and data analysis.
- it provides multidimensional array objects(ndarray) and a large collection of mathematical procedures to process them.
- Numpy Array is optimized array structure.
- Very Efficient for mathematical operations.
- Multi-Dimensional Arrays are great for linear lgebra and matrix operations.
- performs operations much faster than pure python lists.
- Mutable,Homogeneos(data type is one type in numpy array) and indexable.
- Free and open-source

In [5]:
import numpy as np
print(np.__version__)

2.3.2


## 1) Creating Numpy Arrays:

In [7]:
#we can create an array by directly converting a list or lit of lists:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(type(arr))
print(arr)


<class 'numpy.ndarray'>
[1 2 3 4 5]


In [8]:
#to create a matrix
my_list=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(my_list)
print(type(my_matrix))
print(my_matrix)


<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#use function help() to give ore info
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

## 2) Built-in Methods to generate arrays:

In [11]:
#like range() function used for list creation, there is arange() function for array creation
my_arr=np.arange(1,11)
print(my_arr)
print(type(my_arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [12]:
#zeros, ones , and eye(identity Matrix)
#zeros(n) creates an n vector of zeros zeros((n,m)) creates an n*m matrix of zeros
#zeros((n,m,k)) creates a 3d matrix of m*k *(2) of zeros
m1=np.zeros(3)
print(m1)
m1=np.zeros((3,4))
print(m1)
m1=np.zeros((4,3,3))
print(m1)


[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [13]:
#ones() same as zeroes but creates a matrix of ones
m1=np.ones(5)
print(m1)
m1=np.ones((3,2))
print(m1)
m1=np.ones((3,2,2))
print(m1)

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [14]:
#eye(n,m) creates a matrix with ones on the main diagonal, it is flexible and the matrix
#doesn't have to be squared
m1=np.eye(3)
print(m1)
m1=np.eye(3,3)
print(m1)
m1=np.eye(5)
print(m1)
m1=np.eye(2,3)
print(m1)
m1=np.eye(3,2)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [15]:
#identity(n) it creates a square matrix of n*n with ones on the main diagonal
m1=np.identity(5)
print(m1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#linspace(start,stop,number of elements) function returns an array with 
#evenly spaced numbers over a specified interval
#the end number is stop and not stop-1 unlike range() or np.arange()
arr=np.linspace(0,100,6)
print(arr)
print(type(arr))
arr=np.linspace(0,100,5)
print(arr)
#if you want to exclude the stop number like range() function set parameter
#enpoint=False
arr=np.linspace(0,100,5,endpoint=False)
print(arr)
arr=np.linspace(0,10,50)
print(arr)

[  0.  20.  40.  60.  80. 100.]
<class 'numpy.ndarray'>
[  0.  25.  50.  75. 100.]
[ 0. 20. 40. 60. 80.]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [17]:
#random functions in numpy 
#rand(),randn(),randint(),uniform(),normal()
#np.random.rand(dimensions)  Generates random numbers from a uniform distribution 
#over the half-open interval [0.0, 1.0) with the given dimensions
my_arr=np.random.rand(3)
print(my_arr)
my_arr=np.random.rand(2,2)
print(my_arr)
my_arr=np.random.rand(3,4,3)
print(my_arr)


[0.77618544 0.48933636 0.16066573]
[[0.24869554 0.95872207]
 [0.25599757 0.69689856]]
[[[0.68732707 0.76834047 0.79714316]
  [0.64763721 0.8608438  0.37773923]
  [0.57314704 0.99869487 0.38883892]
  [0.3700005  0.60696069 0.46628414]]

 [[0.08166653 0.43051729 0.108098  ]
  [0.95156847 0.59587034 0.75728619]
  [0.36824098 0.28833377 0.13621066]
  [0.67213467 0.54568776 0.533897  ]]

 [[0.46070875 0.05411324 0.21668337]
  [0.38499377 0.68068586 0.04647299]
  [0.90150384 0.89618994 0.31581661]
  [0.68152454 0.88651367 0.17655908]]]


In [18]:
#randn(dimensions) Generates random numbers from a standard normal (Gaussian) distribution.
#the numbers generated have a mean of 0 and a standard deviation of 1
my_arr=np.random.randn(5)
print(my_arr)
my_arr=np.random.randn(2,2)
print(my_arr)
my_arr=np.random.randn(2,3,3)
print(my_arr)

[-1.52398526 -0.54071667  0.44926347  0.1214128  -0.29789991]
[[-0.59662176  2.59169308]
 [-0.60697652 -0.88409935]]
[[[ 0.10512224 -0.60653859  0.7731141 ]
  [-0.01657414  1.08719047  0.42707744]
  [ 0.33395827  0.01159796  0.24299225]]

 [[ 2.29329177  0.76969385  2.300708  ]
  [ 0.71242701 -1.90979742  0.37157359]
  [ 0.67379606 -0.31917086  1.05067086]]]


In [19]:
#randint(start,stop,size)Purpose: Generates random integers from a specified range.
#where stop is exclusive size is given as dimensions
my_arr=np.random.randint(0,10,5)
print(my_arr)
my_arr=np.random.randint(0,10,(3,3))
print(my_arr)
my_arr=np.random.randint(0,10,(2,3,4))
print(my_arr)


[0 6 1 0 1]
[[0 5 5]
 [7 2 7]
 [6 4 6]]
[[[0 9 9 0]
  [7 0 9 1]
  [3 4 0 4]]

 [[7 9 7 8]
  [9 4 6 4]
  [5 2 5 1]]]


In [20]:
#uniform(start,stop,size) uniform is same as randint but it returns floats
my_arr=np.random.uniform(0,10,5)
print(my_arr)
my_arr=np.random.uniform(0,10,(3,3))
print(my_arr)
my_arr=np.random.uniform(0,10,(2,3,4))
print(my_arr)

[3.14568489 4.76428684 2.54315831 5.53210603 5.91554085]
[[6.29590863 7.71471954 7.21902583]
 [3.70505856 2.24785069 4.19380353]
 [3.21792757 9.05624157 4.20507945]]
[[[9.03283957 0.18100029 4.46589117 4.10592843]
  [3.71579192 9.84387382 9.18428167 4.166953  ]
  [0.75354469 0.56311692 2.61819176 6.56708102]]

 [[2.16046894 7.96688004 1.42708314 0.05093604]
  [1.25353961 2.46083006 5.11798711 8.03711889]
  [9.33030822 5.94434396 4.61083955 7.98983653]]]


In [21]:
#normal(mean,std_deviation,size) generates random numbers according to gaussaian distribution
#over given mean and standard deviation, with the diensions of the array given in size
my_arr=np.random.normal(10,1,10)
print(my_arr)
my_arr=np.random.normal(20,5,100)
print(my_arr)
my_arr=np.random.normal(-5,2,(3,3))
print(my_arr)
my_arr=np.random.normal(100,10,(2,5,4))
print(my_arr)


[ 9.45420751  9.68330562  8.37832642 11.29282594 10.02182162  9.00756098
  9.30701139 10.3906884  11.36395036  8.74646282]
[26.55226102 27.70520702 20.07103832 24.36190166 22.39650458 16.17006104
 19.1193266  15.79371109 22.59225036 22.84205819 19.22299462 22.6459756
 16.25880865 19.98515346 24.27045956 22.50523397 16.38799835 21.29827326
 18.53846697 20.77481063 16.75753725 14.39696038 34.91898912 25.4752191
 21.38309604 23.8936819  10.68612439 19.06977512 16.38709777 24.26354321
 17.61501883 21.73920309 19.78740167 17.15607628 24.68572682 15.20906459
 21.50171103 20.18648202 21.10996245 18.59250649 21.72061395 18.28325249
 25.52832815 28.11588687 32.09469816 17.07028496 29.06148562 15.73617857
 22.79455935 12.62371536 17.55192266 22.66935767 23.19556118 22.69245673
 21.0657623  16.44104392 22.8224014  20.04764743 21.54968863 18.29284826
 19.11857164 23.26382322 24.44726794 21.01281949 25.30981305 20.99503242
 13.10005626 16.54283097 20.36600875 21.74421003 19.7141387  17.16561965
 20

## 3)Numpy methods:

In [23]:
#max(), min(), argmax(),argmin()
#max(),min() find maximum or minimum values in an array 
#argmax(), argmin() returns the index of the maximum or minimum value in the array 
my_arr=np.random.randint(0,100,20)
print(my_arr)
print(my_arr.max(),my_arr.min(),my_arr.argmax(),my_arr.argmin())

[74 74 85  8 55 77 46 55 19 17  6 49 27 63 65 92 14 63 26 63]
92 6 15 10


In [24]:
#reshape()  it changes the shape of an array without changing its data. 
#It returns a new array with the specified shape, it doesn't change the original array.
#The total number of elements in the new array must be 
#the same as the total number of elements in the original array.
#syntax array.reshape(size) ,np.reshape(array,size)
my_arr=np.array([[1,2,3,4],[5,6,7,8]])
x=my_arr.reshape((4,2))
print(x,'\n')
#Using -1 for an Unknown Dimension
#A powerful feature of reshape() is using -1 as one of the dimensions.NumPy will 
#automatically calculate the correct size for that dimension 
#based on the total number of elements.
my_arr=np.random.randint(0,100,(4,3))
print(my_arr,'\n')
x=my_arr.reshape(2,-1)
print(x,'\n')
x=my_arr.reshape(-1,4)
print(x,'\n')




[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[18 89 91]
 [43 68  5]
 [13 49 11]
 [15 34 93]] 

[[18 89 91 43 68  5]
 [13 49 11 15 34 93]] 

[[18 89 91 43]
 [68  5 13 49]
 [11 15 34 93]] 



In [25]:
#to get the shape of the array use shape() function
print(np.shape(x))
#to get the size of array(number of elements)
#size()
print(np.size(x))
#to get the dimensions of an array ndim() function
print(np.ndim(x))
#to get the datatype stored in the array dtype attribute
print(x.dtype)
#to convert a datatype of an array use astype(new_type), it will return  new array 
#with the new datatype but it will not convert the original array
y=x.astype(np.float64)
print(y.dtype)
print(y)

(3, 4)
12
2
int32
float64
[[18. 89. 91. 43.]
 [68.  5. 13. 49.]
 [11. 15. 34. 93.]]


## 4)Numpy Indexing and Slicing:

**Indexing for Numpy arrays**:
1. 1d indexing(Vectors)
2. 2d indexing(Matrices)
3. nd indexing
4. fancy indexing

In [28]:
#for 1d vectors accessing an element by its index
arr=np.arange(30,40)
print(arr)
print(arr[5])
arr[1]=41
print(arr)
print(arr[:])
print(arr[::-1])
print(arr[1:9])
arr[1:3]=(1,2) #give a list or tuple of the esxact number of elements
print(arr)
#arr[1:6]=[3,4] error you must enter the exact number of elements
arr[3:6]=90 #it will replace all elements in the range with the given value
print(arr)
arr[3:6]=43.5
print(arr) #it will cast the float value to int to fit inside the array

arr[:]=5
print(arr)

#copy() and sort()
x=arr.copy()
print(x)
arr=np.arange(30,50,2)
print(arr)
x=arr[::-1]
print(x)
x.sort()
print(x)
x=arr.view() #view() makes x and arr hold the same data a change in x is a change in arr
print(x)
x[:]=1
print(arr)

[30 31 32 33 34 35 36 37 38 39]
35
[30 41 32 33 34 35 36 37 38 39]
[30 41 32 33 34 35 36 37 38 39]
[39 38 37 36 35 34 33 32 41 30]
[41 32 33 34 35 36 37 38]
[30  1  2 33 34 35 36 37 38 39]
[30  1  2 90 90 90 36 37 38 39]
[30  1  2 43 43 43 36 37 38 39]
[5 5 5 5 5 5 5 5 5 5]
[5 5 5 5 5 5 5 5 5 5]
[30 32 34 36 38 40 42 44 46 48]
[48 46 44 42 40 38 36 34 32 30]
[30 32 34 36 38 40 42 44 46 48]
[48 46 44 42 40 38 36 34 32 30]
[1 1 1 1 1 1 1 1 1 1]


In [29]:
#for 2d arrays matrices:

In [30]:
arr=np.reshape(np.linspace(0,90,9),(3,3))
print(arr)

[[ 0.   11.25 22.5 ]
 [33.75 45.   56.25]
 [67.5  78.75 90.  ]]


In [31]:
#indexing
#syntax: arr_name[row_index][column_index] or arr_name[row_index,column_index]
print(arr[2][1])
print(arr[2,1])
arr[1][1]=0
arr[2,2]=7
print(arr)



78.75
78.75
[[ 0.   11.25 22.5 ]
 [33.75  0.   56.25]
 [67.5  78.75  7.  ]]


In [32]:
#slicing 
#syntax arr_name[ row:row,col:col] 
#if you want to get 1 row or 1 col  arr_name[row_num,col:col] will only get the specific
#row ,arr_name[row:row,col_num] will only get from the specific col
arr=np.reshape(np.arange(1,9+1),(3,3))
print(arr,'\n')
print(arr[:,1],'\n')# get all rows,and column 1 only
print(arr[:,:],'\n')#will get the whole array
print(arr[1:,1:],'\n') #will get the bottom right corner
print(arr[:,2]) #will get the last column

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[2 5 8] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[5 6]
 [8 9]] 

[3 6 9]


In [33]:
#assigning values with slicing ,must assign exact number of values if will be passed
#in iterable
arr[1,:]=[1,7,8]
print(arr)
#arr[1,:]=[1,2] this will give error
arr[2,:]=10 #this will make all values in row 2 = 10
print(arr,'\n')
arr=np.reshape(np.arange(1,9+1),(3,3))
print(arr,'\n')
print(arr[::-1,:],'\n')#this will print the rows in reverse order
print(arr[:,::-1],'\n') #this will print the column in reverse order
print(arr[::-1,::-1],'\n')#this will print the matrix with reversing columns and rows

[[1 2 3]
 [1 7 8]
 [7 8 9]]
[[ 1  2  3]
 [ 1  7  8]
 [10 10 10]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[7 8 9]
 [4 5 6]
 [1 2 3]] 

[[3 2 1]
 [6 5 4]
 [9 8 7]] 

[[9 8 7]
 [6 5 4]
 [3 2 1]] 



In [34]:
#fancy indexing
#fancy indexing allows you to select entire rows or columns out of order
arr=np.random.randint(1,100,(10,10))
print(arr)

[[48 47 34 87 93 64 84 17 15 91]
 [ 8 11 20 96  1 63 25 49 78 74]
 [14 97 95 44 70 59 98 68 24 63]
 [68 72 24 12 11 84 41 44 54 37]
 [29 18 53 74 97  4 96 76  7  8]
 [26 99 74 99 17 19  3 92 61 25]
 [99 57 40 97 25 36 68 73  2 98]
 [67 43 20 15 74 49 31 51 44 16]
 [51 20 72 66 85 33 99  3 29 59]
 [87 80 14 95 94 20 62 69 60  4]]


In [35]:
#syntax: arr_name[[wanted rows index in a list]]
print(arr[[2,5,9]],'\n')
#its allowed in any order
print(arr[[7,6,0]],'\n')
#you can get certain columns out of these rows 
print(arr[[2,5,9],[3]],'\n')
print(arr[[2,5,9],3:6],'\n')



[[14 97 95 44 70 59 98 68 24 63]
 [26 99 74 99 17 19  3 92 61 25]
 [87 80 14 95 94 20 62 69 60  4]] 

[[67 43 20 15 74 49 31 51 44 16]
 [99 57 40 97 25 36 68 73  2 98]
 [48 47 34 87 93 64 84 17 15 91]] 

[44 99 95] 

[[44 70 59]
 [99 17 19]
 [95 94 20]] 



## Adding and removing elements:

In [37]:
arr=np.array([1,2,3])

In [38]:
#np.append(arr,element) The np.append() function is used to add values to 
#the end of an array. It creates and returns a new array with the appended values.
#The np.insert(arr,indeces,values) function inserts values into an array at a specified index 
#or indices. It also returns a new array.
#np.delete(arr,indeces), which removes elements from an array at a specified index or indices.
#It also returns a new array.
arr=np.array([1,2,3,4,5,6,7,8])
x=np.append(arr,10)
print(x)

arr=x
x=np.insert(arr,4,32)
print(x)
arr=x

x=np.insert(arr,[4,6],[55,77]) #inseting multiple elements at different indeces
print(x)
arr=x

x=np.delete(arr,4)
print(x)
arr=x
x=np.delete(arr,[1,2,3]) #removing multiple elements fro different indeces
print(x)
arr=x

[ 1  2  3  4  5  6  7  8 10]
[ 1  2  3  4 32  5  6  7  8 10]
[ 1  2  3  4 55 32  5 77  6  7  8 10]
[ 1  2  3  4 32  5 77  6  7  8 10]
[ 1 32  5 77  6  7  8 10]


## Combining and splitting

In [74]:
a=np.array([1,2,3])
b=np.array([4,5,6])
#to combine two arrays  we use np.concatenate((arr1,arr2)), it returns a new array, pass them
#in a tuple or list
c=np.concatenate([a,b])
print(c)
#to combine two arrays vertically we use np.vstack((arr1,arr2)) will make rows
c=np.vstack((a,b))
print(c)
#to combine two arrays horizontally we use np.hstack((arr1,arr2))
c=np.hstack((a,b))
print(c)



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [72]:
#splitting
#to split an array we use np.split(arr,number of splits)
x,f,g=np.split(c,3)
print(x)
print(f)
print(g)
v=np.reshape(np.arange(1,12+1),(4,3))
a,b,e,d=np.split(v,4)
print(a,b,e,d)

[1 2]
[3 4]
[5 6]
[[1 2 3]] [[4 5 6]] [[7 8 9]] [[10 11 12]]


## Numpy Operations

**Numpy Operations:**
1. Arithmetic and Logic operations.
2. Universal Array Functions.

In [88]:
#Arithmetic operations: it works on ndarray
arr=np.arange(0,10)
print(arr)
print(arr+3)
print(arr-1)
print(arr*2)
print(arr/0)# note 0/0 gives nan, any number/0 gives inf 
print(arr/2)
print(arr+arr)
print(arr-arr)
print(1/arr)
print(3**arr)
print(arr**3)

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11 12]
[-1  0  1  2  3  4  5  6  7  8]
[ 0  2  4  6  8 10 12 14 16 18]
[nan inf inf inf inf inf inf inf inf inf]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[    1     3     9    27    81   243   729  2187  6561 19683]
[  0   1   8  27  64 125 216 343 512 729]


C:\Users\dell\AppData\Local\Temp\ipykernel_5032\2222561942.py:7: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)# note 0/0 gives nan, any number/0 gives inf
C:\Users\dell\AppData\Local\Temp\ipykernel_5032\2222561942.py:7: RuntimeWarning: invalid value encountered in divide
  print(arr/0)# note 0/0 gives nan, any number/0 gives inf
C:\Users\dell\AppData\Local\Temp\ipykernel_5032\2222561942.py:11: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [92]:
#logic operations:works on ndarray
#logic operations occurs element wise and return an array of logic results for each element
print(arr>3)
print(arr==3)
print(arr<=3)

[False False False False  True  True  True  True  True  True]
[False False False  True False False False False False False]
[ True  True  True  True False False False False False False]


In [106]:
#universal array functions:
#np.max(arr,axis),np.min(arr,axis),np.average(arr),np.sum(arr)
#np.max(arr,axis=0) gets the max value in each column
#np.max(arr,axis=1) gets the max value in each row
#for min the same axis=0 for cols, axis =1 for rows
#for avergae and sum the same
arr=np.reshape(np.random.randint(1,100,12),(4,3))
print(arr)
max_=np.max(arr)
print(max_)
min_=np.min(arr)
print(min_)
avg=np.average(arr)
print(avg)
sum_=np.sum(arr)
print(sum_)
max_cols=np.max(arr,axis=0)
print(max_cols)
max_rows=np.max(arr,axis=1)
print(max_rows)
avg_cols=np.average(arr,axis=0)
print(avg_cols)
avg_rows=np.average(arr,axis=1)
print(avg_rows)
sum_cols=np.sum(arr,axis=0)
print(sum_cols)
sum_rows=np.sum(arr,axis=1)
print(sum_rows)

[[49 66 30]
 [41 95 43]
 [40 97 71]
 [21 43 76]]
97
21
56.0
672
[49 97 76]
[66 95 97 76]
[37.75 75.25 55.  ]
[48.33333333 59.66666667 69.33333333 46.66666667]
[151 301 220]
[145 179 208 140]


In [118]:
#sqrt(),exp(),log(),sin
#power()
arr=np.arange(1,100,10)
print(arr,'\n')

#np.sqrt(arr):calculates the square root of each element in an array.
sqrt=np.sqrt(arr)
print(sqrt,'\n')
#np.exp()computes the exponential of each element in an array, 
#which means it raises the mathematical constant e (approximately 2.71828) 
#to the power of each element. e^(each element in array)
exp=np.exp(arr)
print(exp,'\n')

#np.log():calculates the natural logarithm of each element in an array. 
#This is the logarithm to the base e. For other bases, 
#you can use np.log2() for base 2 or np.log10() for base 10.
loge=np.log(arr)
print(loge,'\n')
#np.sin():computes the sine of each element in an array. 
#The input values are treated as angles in radians.
#note convert angles from degree to radians before using sin or cos or tan
angles=np.array([0,0.5*np.pi,np.pi,1.5*np.pi,2*np.pi])
sins=np.sin(angles)
print(sins)
#np.power():raises each element in one array to the power of the corresponding 
#element in a second array.



[ 1 11 21 31 41 51 61 71 81 91] 

[1.         3.31662479 4.58257569 5.56776436 6.40312424 7.14142843
 7.81024968 8.42614977 9.         9.53939201] 

[2.71828183e+00 5.98741417e+04 1.31881573e+09 2.90488497e+13
 6.39843494e+17 1.40934908e+22 3.10429794e+26 6.83767123e+30
 1.50609731e+35 3.31740010e+39] 

[0.         2.39789527 3.04452244 3.4339872  3.71357207 3.93182563
 4.11087386 4.26267988 4.39444915 4.51085951] 

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


## Dot product

In [127]:
mat=np.arange(9).reshape(3,3)
vec1=np.array([1,2,3])
#np.dot(arr1,arr2) akes dot product between matrices
print(np.dot(vec1,mat))

[24 30 36]


## Numpy time efficiency:

In [137]:
import time

start_time = time.time()
my_arr=np.arange(100000000)
b=0
for i in my_arr:
    b=b+i
print(f'Sum using loop:\n{b}\nTime:\n{time.time()-start_time}')
print('-'*40)

start_time = time.time()

print(f'Sum using vectorized implementation:\n{my_arr.sum()}\nTime:\n{time.time()-start_time}')

Sum using loop:
4999999950000000
Time:
21.632014989852905
----------------------------------------
Sum using vectorized implementation:
4999999950000000
Time:
0.35191893577575684
