## 🟢 Section 1: Creating Arrays

## Q: Create an array from 1 to 10. Extract only even numbers.

### Answer 

In [47]:
import numpy as np
evens=np.array([x for x in range(1,11) if x%2==0 ])
print(evens)


[ 2  4  6  8 10]


# Great Job!

## 🟢 Section 2.1: arange

## Q: Use arange to create an array from 0 to 20 with step 5.


### Answer 

In [49]:
arr=np.arange(0,21,5)
print(arr)

[ 0  5 10 15 20]


# Great Job!

## 🟢 Section 2.2: zeros, ones, eye

## Q: Create a 3×3 matrix of ones.

### Answer 

In [53]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Great Job!

## 🟢 Section 2.3: linspace

## Q: Use linspace to generate 5 numbers between 0 and 1.

### Answer 

In [55]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


# Great Job!

## 🟢 Section 2.4: rand, randn, randint

## Q: Create a 1D array with 5 random integers between 1 and 20.

### Answer 

In [57]:
arr=np.random.randint(1,20,5)
print(arr)

[ 5 15 14 17 10]


# Great Job!

## 🟢 Section 2.5: min, max, argmin, argmax

## Q: Create an array of 20 random integers between 1 and 500. Find the maximum number.


### Answer 

In [61]:
arr=np.random.randint(1,500,20)
print(arr)
max_=np.max(arr)
print(max_)

[376 330 204 317 288 210 132 260 237 385 264 158  95   7 315 445 175  60
 273 164]
445


# Great Job!

## 🟢 Section 3: Reshape

## Q: Create an array from 1 to 9, then reshape it into 3×3.


### Answer 

In [63]:
arr=np.reshape(np.arange(1,9+1),(3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Great Job!

## 🟢 Section 4: Indexing & Selection

## Q: Create a 3×3 array from 1 to 9. Extract the last row.

## Extract the last row.

## Extract the first column.

### Answer 

In [65]:
arr=np.reshape(np.arange(1,9+1),(3,3))
print(arr)
first_col=arr[:,0]
last_row=arr[2,:]
print(first_col)
print(last_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[7 8 9]


# Great Job!

## 🟢 Section 5: Fancy Indexing

## From [5,10,15,20,25], extract elements at indices [0,2,4].

### Answer 

In [67]:
arr=np.array([5,10,15,20,25])
print(arr[[0,2,4]])

[ 5 15 25]


# Great Job!

## 🟢 Section 6: Arithmetic

## Q: Given two matrices:

A = [[2,4,6],
     [1,3,5]]

B = [[10,20,30],
     [40,50,60]]

## Add them. Multiply element-wise. Compute the dot product.

### Answer 

In [71]:
a=np.array([[2,4,6], [1,3,5]])
b=np.array( [[10,20,30], [40,50,60]])
c=a+b
print(c)
c=a*b
print(c)
c=np.dot(a,b.T) #.T makes a transpose of the matrix
print(c)

[[12 24 36]
 [41 53 65]]
[[ 20  80 180]
 [ 40 150 300]]
[[280 640]
 [220 490]]


# Great Job!

## 🟢 Section 7: Universal Functions

## Q: Compute the square root of each element in [1,4,9,16].

### Answer 

In [75]:
arr=np.array([1,4,9,16])
sqrt=np.sqrt(arr)
print(sqrt)

[1. 2. 3. 4.]


# Great Job!