# Numpy Array Creation

### Import Numpy

In [3]:
import numpy as np

### Create an array of numpy dimensions 4x4 filled with zeros.
__Expected result:__

```
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
```
__Tip:__ Use the _np.zeros()_ function.

In [5]:
arr=np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


###Create an array of numpy dimensions 10.x10. filled with number 255 .




__Expected result:__
```
array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])
```

__Tip:__ Use the _np.ones()_ or _np.full()_ functions.

In [11]:
# Solution 1
arr=np.ones((10,10))*255
print(arr)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [9]:
# Solution 2
arr=np.full((10,10),255) #np.full(shape,fill_value)
print(arr)

[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


### Build a 6x6 two-dimensional array - identity matrix. Use the _int_ data type.

__Expected result:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```
.


In [15]:
arr=np.identity(6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Create a one-dimensional numpy array (vector) consisting of 11 equally spaced points from the interval  [0, 1].

__Expected result:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Tip:__ Use the _np.linspace()_ function.



In [17]:
arr=np.linspace(0,1,11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Create an array of all the odd integers from 10 to 100

```
array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])
```


In [19]:
arr=np.arange(11,101,2)
print(arr)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


### Create an array of 5x5 random numbers from a uniform distribution

__Tip:__ Use the _np.random.rand()_ function.



In [25]:
arr=np.reshape(np.random.rand(25),(5,5))
print(arr)

[[0.60102911 0.01149183 0.2959599  0.53809468 0.03158417]
 [0.28423606 0.59318437 0.82006567 0.46527077 0.65650126]
 [0.03200732 0.51610014 0.17689613 0.65159448 0.7971699 ]
 [0.15548998 0.80152698 0.14240682 0.77221218 0.79320685]
 [0.56998349 0.72068069 0.09151423 0.66019831 0.15110078]]


### Create an array of 10 random numbers from a standard normal distribution

__Tip:__ Use the _np.random.randn()_ function.



In [27]:
arr=np.random.randn(10)
print(arr)

[-0.56321308  0.72426808  0.41314191 -0.87888535  0.44633002  1.94362321
 -0.15957928  0.35173043 -0.42575868 -0.02674629]


## Build the two-dimensional 6x6 size array below:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Tip:__ Use the _np.diag()_ function.



The np.diag() function in NumPy is a versatile tool for working with the diagonal of a 2D array. It has two main uses:

Extracting the diagonal elements of a 2D array.

Creating a 2D array with a 1D array on the specified diagonal.

1. Extracting the Diagonal
When you pass a 2D array to np.diag(), it returns a 1D array containing the elements on the main diagonal.

Syntax: np.diag(array, k=0)

array: The 2D array from which to extract the diagonal.

k: The offset of the diagonal. k=0 is the main diagonal, k>0 is an upper diagonal, and k<0 is a lower diagonal.

2. Creating a Diagonal Matrix
When you pass a 1D array to np.diag(), it creates a 2D array with the elements of the 1D array on the main diagonal and zeros elsewhere.

Syntax: np.diag(1d_array, k=0)

1d_array: The array whose elements will form the diagonal.

k: The offset of the diagonal.


In [30]:
# Solution 1
arr=np.arange(6)
arr=np.diag(arr)
print(arr)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [ ]:
# Solution 2


# Numpy Array Operations

### Combine the following arrays: $ A $ and $ B $ into one array.

```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```

__The expected result:__

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```




In [34]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

c=np.concatenate((A,B))
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


### The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return with maximum values for a given row.



In [38]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])


In [42]:
max_row_1=np.max(A[1])
print(max_row_1)

0.8


### The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return with sum of columns.

.


In [ ]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])


In [44]:
sum_cols=np.sum(A,axis=0)
print(sum_cols)

[0.7 0.9 1.4]


### Extract all elements of the $ A $ array with a value greater than 8.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [46]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])



In [54]:
#boolean indexing 
print(A[A>8]) #A>8 is a condition applied to the array each element in the array gives true or false,
#when you say arr_name[boolean condition] it returns an array with all values that has true for the condition

[ 9.99  9.99 14.99]


### Present the following $ A $ two-dimensional array as a "flattened" one-dimensional array.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```


In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])



In [58]:
A=np.reshape(A,np.size(A))
print(A)

[ 4.99  3.49  9.99  1.99  9.99  4.99 14.99  2.39  7.29]


### The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return Size , shape , datatype of array A

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])



In [60]:
np.size(A)

9

In [62]:
np.shape(A)

(9,)

In [64]:
A.dtype

dtype('float64')

### The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return last row in array A

In [66]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])



In [76]:
rows,cols=np.shape(A)
rows-=1
cols-=1
A[rows]
#or
A[2]

array([14.99,  2.39,  7.29])

### The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return frist column in array A

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])



In [78]:
A[:,0]

array([ 4.99,  1.99, 14.99])

### The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return transpose of array A

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

A

In [80]:
# Solution 1
A.T

array([[ 4.99,  1.99, 14.99],
       [ 3.49,  9.99,  2.39],
       [ 9.99, 14.99,  7.29]])

In [84]:
# Solution 2
np.array([A[:,0],A[:,1],A[:,2]])

array([[ 4.99,  1.99, 14.99],
       [ 3.49,  9.99,  2.39],
       [ 9.99, 14.99,  7.29]])

### The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the inverse matrix to the $ A $ matrix.



In [ ]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

A

In [90]:
inv=np.linalg.inv(A)  #for getting inverse use np.linalg.inv(arr)
print(inv)

[[-0.06977615  0.00295315  0.08954678]
 [-0.39638004  0.21379777  0.10356763]
 [ 0.27342836 -0.07616521 -0.08090986]]


### The following array (square matrix) $ A $ is given:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Compute the determinant of the $ A $ matrix.




In [ ]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

A

In [94]:
det=np.linalg.det(A) #for determinant use np.linalg.det(arr)
print(det)

-530.2815000000003


### The following two arrays $ A $ and $ B $ are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```

Add array A and array B .

__Expected result:__
```
array([[7, 7, 11, 7],
       [11, 6 , 3, 11]])
```

In [96]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])



In [98]:
# Solution 1
A+B

array([[ 7,  7, 11,  7],
       [11,  6,  3, 11]])

In [ ]:
# Solution 2


### Two two-dimensional arrays are provided, numpy $ A $ and $ B $.  
$ A $ - dimension matrix $ (3, 2) $  
$ B $ - dimension matrix $ (2, 3) $  
```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Perform matrix multiplication of $ A $ and $ B $ arrays.



In [102]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])


In [104]:
# Solution 1
np.dot(A,B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

In [ ]:
# Solution 2
